Time::DATE_FORMATS[:default] = "%b %d, %Y"
Date::DATE_FORMATS[:default] = "%b %d, %Y"
DateTime::DATE_FORMATS[:default] = "%b %d, %Y"
Time::DATE_FORMATS[:long] = "%B %d, %Y"
Date::DATE_FORMATS[:long] = "%B %d, %Y"
DateTime::DATE_FORMATS[:long] = "%B %d, %Y"
